### PR TITLE
Allow database connection via socket

### PR DESCRIPTION
**Pull request by whitemerry**
This PR adds `PERCONA_DB_SOCKET` environment variable support and configuration property `socket` that has higher priority than `host` and `port` configuration.

Tested on staging environments with proxysql socket connection.

Created by @Levii01

### CODE REVIEW

**Review by Levii01 — APPROVED** [review]
🎖️

**Review by krzysztofjablonski — APPROVED** [review]

**Comment by whitemerry** [comment]
@benlangfeld @xjunior looks like the (2.5, 6.1.0) and (2.6, 5.2.0) fails.

I have did prepared local environment: Ruby 2.6.6 with Rails 5.2.0.

Random run: `267 examples, 0 failures, 3 pending` on `seed 18011`.

Run with seed from GitHub Actions: 
```
$ bundle exec rspec --seed 27815
[...]

  1) Departure logging when the migration logging is disabled doesn't send the output to stdout
     Failure/Error:
       expect do
         ActiveRecord::Migrator.new(direction, migration_fixtures, ActiveRecord::SchemaMigration, 1).migrate
       end.to_not output.to_stdout
     
       expected block to not output to stdout, but output "\n   -> Running pt-online-schema-change -h \"localhost\" -P 3306 -u root [filtered_password] --execu...Event  Count\n# ====== =====\n# INSERT     1\nSuccessfully altered `departure_test`.`comments`.\n\n"
     # ./spec/integration_spec.rb:36:in `block (4 levels) in <top (required)>'
     # ./spec/integration_spec.rb:31:in `block (4 levels) in <top (required)>'

Finished in 43.38 seconds (files took 1.05 seconds to load)
267 examples, 1 failure, 3 pending
```

I don't think it's related to our changes.
Should I create new ticket related to it?

**Comment by benlangfeld** [comment]
> I don't think it's related to our changes. Should I create new ticket related to it?

Sure, that'd be great.

**Comment by whitemerry** [comment]
@benlangfeld double-checked - specs failure with seed `27815` on `Ruby 2.6.6` with `Rails 5.2.0` happens on both, our branch and master.

**Pull request merged**
