### PR TITLE
Add mysql2 0.5.2 gem support

### PR DESCRIPTION
**Pull request by saulm**

### CODE REVIEW

**Comment by saulm** [comment]
@guilleiguaran is this something doable?

**Comment by sauloperez** [comment]
IMO we should execute the test suite with at least mysql2 0.5.2.

**Comment by saulm** [comment]
@sauloperez I ran the specs with mysql2 0.5.2 and 0.5.1

**Comment by sauloperez** [comment]
Sorry, I meant in CI this way we ensure tests pass with the latest supported version.

**Comment by saulm** [comment]
This PR ran travis with 0.5.2 https://travis-ci.org/departurerb/departure/builds/415922252#L616

@sauloperez

**Comment by sauloperez** [comment]
Ouch, right! that good looks good to me then. Agree @guilleiguaran @wyhaines ?

**Comment by guilleiguaran** [comment]
Looking good in my opinion

**Pull request merged**
