### PR TITLE
Allow mysql2 0.5.4

### PR DESCRIPTION
**Pull request by davidenglishmusic**
https://github.com/departurerb/departure/issues/79

### CODE REVIEW

**Review by benlangfeld — APPROVED** [review]

**Comment by benlangfeld** [comment]
@sikachu @ionut is it possible to merge this and cut a release?

**Comment by benlangfeld** [comment]
@sikachu @ionut998 Would you be willing to add me as a maintainer of this package?

**Comment by ionut998** [comment]
@benlangfeld I am only a contributor here and I don’t have permissions to add you as a maintainer. @sikachu should be able to merge this or add you as a maintainer. It looks like there are some failing tests on Ruby 3.

**Comment by xjunior** [comment]
@davidenglishmusic can you update your PR?

**Pull request merged**
