### PR TITLE
Add SSL connection support

### PR DESCRIPTION
**Pull request by saulm**
This PR adds support for connecting to the MySQL server over SSL if configured (sslca present on the adapter options)

### CODE REVIEW

**Comment by saulm** [comment]
Not sure why the build failed, here it is on my fork: https://travis-ci.org/saulm/departure/builds/490388351

**Comment by sauloperez** [comment]
Just a failed installation in Travis. A rebuild should do

**Comment by sauloperez** [comment]
@saulm I updated the CHANGELOG myself so ready to merge :tada: Would you mind documenting in the README how to provide the SSL connection details in another PR?

**Comment by saulm** [comment]
Will do @sauloperez

**Pull request merged**
